### ISSUE TITLE
Builders Challenge page snag list

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#114]
- [x] Hero formatting - background needs stretching a little more?
- [x] Column block - can we constrain this with its own layout wrapper?
- [x] in-page anchor link to #guidelines EDIT: deferred till post-MVP and ticketed
- [x] Centre-align layout for bio grid, or not? EDIT: NOT

**Comment by craigcook** [comment]
So I think we may need to make some kind of special component for the sponsor grid if we really want to vertically center the logos. Using any combination of other existing components (cards, pictos, etc) doesn't get that effect without breaking other instances of those same components. 

Short of making a custom component, we could just accept that they won't be vertically centered, or we could make them all perfect square images with transparent pixels. I'm favoring the latter option as best and easiest, honestly. Then it can just be a card layout or even a column layout with plain ol' images.

**Comment by stevejalim** [comment]
Yeah I think transparent square images is the way to go here, too. Thanks
for exploring and sorry for the pain

**Comment by stevejalim** [comment]
@craigcook Don't want to clash with any WIP you have, but if you haven't made any code changes related to this, would you like me to back out the flexbox stuff I added to CaptionedImageBlock? Happy to!

**Comment by craigcook** [comment]
> @craigcook Don't want to clash with any WIP you have, but if you haven't made any code changes related to this, would you like me to back out the flexbox stuff I added to CaptionedImageBlock? Happy to!

I've backed those out, will have a PR in a bit with a batch of CSS fixes.

**Comment by craigcook** [comment]
I think we've covered all these. If we find more problems with this page we can open new issues.
