### ISSUE TITLE
CDN configuration and caching

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#121]
Two things

- [X] At the moment we're sending the `Vary:Cookie` header, which effectively renders the CDN as a pass-through, not a cache. this applies to statics as well as HTML pages.
- [ ] The cache-control max-age param we're seeing for deployed sites is only 3600s compared to a long-long expiry one that is set by whitenoise. Is something [re]setting that along the way?

**Comment by stevejalim** [comment]
@bkochendorfer Just to capture the info in context here, when I hit the pods directly, I do get the expected (long TTL) cache-control headers, so something looks like it is rewriting them between the k8s pods and the end client - something at the LB or CDN layers?

**Comment by bkochendorfer** [comment]
I this this is resolved
