### ISSUE TITLE
Limit ColorField to a set of approved, accessible color options

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#212]
...Plus have some validation on selected values to ensure accessibility needs are met (would need to take in to consideration which theme was also selected along with the BG color)

...Plus map the approved choices to pre-defined CSS classes, so we can avoid inline styles

---

Steps:

- [ ] Define allowed colour options
- [ ] Add specific CSS classes for these options
- [ ] Add new ColorField implementation that has these options as the only selectable values, rather than being a color picker - an entirely new field called a `ColorSelect` seems to make sense
- [ ] Update the component(s) that use this field to use the new one instead, falling back to the old value for now, until a new one is selected
- [ ] Hide the old field in the CMS UI, but don't drop the field from the database yet
- [ ] Rollout and get all sites switched over to using the new picker
- [ ] Follow-up with a separate PR that drops the field

**Comment by stevejalim** [comment]
@craigcook I'm v happy to take this on, as it's not FE-specific, but I'd welcome your advice on what the allowed set(s) of colours should be

**Comment by stevejalim** [comment]
We'll also need to think about a migration/rollout strategy for futuremo, which is using inline styles for colours, but that could be as simple as 'quickly pick a new colour after rollout"

**Comment by craigcook** [comment]
That all sounds like a good approach. I'm only hesitant to commit to a color palette until we have updated brand guidelines. We could pick colors from the current branding but we know they'll be changing at some point in the not-too-distant future.
