### ISSUE TITLE
Links authored in markdown blocks are missing `href` attributes

### ISSUE THREAD

**Issue by johnshaughnessy** [mozmeao/birdbox#300]
Markdown links in markdown blocks in wagtail are converted to HTML anchor elements `<a>` but they do not have `href` attributes. (Screenshots attached).

![snip_2024_02_15_13_45_17](https://github.com/mozmeao/birdbox/assets/4072106/5ea5108a-bb8d-4152-b897-504cb5900dc0)
![snip_2024_02_15_13_43_14](https://github.com/mozmeao/birdbox/assets/4072106/469ea136-f87c-4d29-a0b8-6ad5e36e72ec)
![snip_2024_02_15_13_40_11](https://github.com/mozmeao/birdbox/assets/4072106/f4c4cca3-2d2d-46f0-abaf-9ad02e262fbb)

**Comment by johnshaughnessy** [comment]
Fixed by #301

**Comment by stevejalim** [comment]
@johnshaughnessy this is live in production now. Thanks for the fix!
