### ISSUE TITLE
(enhancement) Allow Table blocks in Blog page + allow Markdown blocks in Innovations content page

### ISSUE THREAD

**Issue by k8si** [mozmeao/birdbox#370]
It would be nice to have "Table" blocks available for Blog posts (currently does not seem to be available). Currently, the Markdown blocks do support tables but formatting the tables inside of the markdown block is very difficult. Would be easier for users to make tables look nice with the Table block.

Also, it seems like  markdown blocks are not available for "Innovations content" page types. Might be easier for users if there were a consistent set of "content import" options available across most page types so, when they are writing their content outside of the CMS, they know what format to write it in such that it can easily be imported into the platform later on.

See thread for context: https://mozilla.slack.com/archives/C04SL757JVC/p1715794724277359

**Comment by stevejalim** [comment]
This is hitting production today. Note that because the blog post layout is narrower than a regular page, tables with 3 columns are probably the most that sensibly fits
