### ISSUE TITLE
Hero Image justified too far to the right

### ISSUE THREAD

**Issue by fernzharp** [mozmeao/birdbox#371]
This issue is showing up on [future.mozilla.org](https://future.mozilla.org/)
The Hero Image is justified too far to the right on extra wide viewports as shown in the screenshots. 
1440 width and below are functioning correctly! 

**3840px width:**

![3840 width](https://github.com/mozmeao/birdbox/assets/60903588/5fef41d9-c73a-42b1-a44d-da82e15fb4b5)

**1440px width:**

![1440 width](https://github.com/mozmeao/birdbox/assets/60903588/085538b0-62a4-4763-98d5-2f956d9a73ee)

**Success Criteria:** 
- [ ] Hero Image is justified to the right but within the contents boundaries on displays greater than 1440px wide.

**Comment by craigcook** [comment]
The Hero component can accept an image background, but the intent of the original design is that such images should be full bleed and fill the background space. You're using a smaller image that should be contained, and for that I'm not sure Hero is the right component. I think you could achieve everything you're after by using a Split instead, though Split currently doesn't support a pre-title "teaser." That might have to be the trade-off until we can make more significant back-end changes.
