### ISSUE TITLE
Add simple 404 and 500 HTML page

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#59]
-[X] Steve to set up the views

- [x] Craig to handle the markup and CSS

**Comment by stevejalim** [comment]
@craigcook no rush but did the wiring up of the 404 and 500 templates. They're unstyled right now - can be anything in there, incl the Mozorg 404/500 content, potentialy

**Comment by craigcook** [comment]
This was done in https://github.com/mozmeao/birdbox/commit/66512211ca6345ff8b8c29a9f48d2fc9c06dfc11
