### ISSUE TITLE
Hero updates

### ISSUE THREAD

**Issue by craigcook** [mozmeao/birdbox#65]
The Hero component needs a few tweaks.

- [x] "Subhead" and "Standfirst" (intro) should be optional fields (they're currently required). Main title should be the only required field.
- [x] Styling of main heading and subheading should be updated. Main heading should be bold, subheading should be regular weight and smaller.
- [x] Adding a background image currently overrides the background color. Background color should be preserved when an image is added.

**Comment by stevejalim** [comment]
Picking up this to do the first and third items
